allowcommands:
  - login
  - register
  - reg
  - zaloguj
  - zarejestruj
  - premium
allowChat: false
maxIPregister: 1
antybot: true
minNicknameLength: 3
maxNicknameLength: 16
safelocation: true
teleportspawn:
  enabled: true
  world: world
  x: 0
  y: 100
  z: 0
  pitch: 0
  yaw: 0
timeout: 60
allowedNicknameCharacters: '[a-zA-Z0-9_]*'
password:
  minlength: 5
  maxlenght: 30
  unsafePasswords:
    - '123456'
    - password
    - qwerty
    - '12345'
    - '54321'
    - '123456789'
    - help
    - premium
recoveryCode:
  enabled: true
  length: 8
sessions:
  enabled: true
  timeout: 25

